[package]
name = "bepinex_helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steamlocate = "1"
pelite = "0.9.1"
semver.workspace = true
